[package]
name = "sunrise"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[dependencies]
egg-mode = "0.8.1"
hyper = "0.10.10"
hyper-native-tls = "0.2.2"
regex = "0.2.1"
chrono = "0.3.0"
serde = "1.0"
toml = "0.4"
slog = "2.0.5"
slog-term = "2.0.1"
clap = "2.24.2"
rustc-perf = { git = "https://github.com/rust-lang-nursery/rustc-perf.git" }
serde_json = "1.0.2"
